/// Calendario del reporte (desde enero de 2024).
table Calendario
	dataCategory: Time

	column Fecha
		dataType: dateTime
		formatString: dd/mm/yyyy
		isKey
		summarizeBy: none
		sourceColumn: Fecha

		annotation UnderlyingDateTimeDataType = Date

	column 'Año'
		dataType: int64
		summarizeBy: none
		sourceColumn: Año

	column Num_mes
		dataType: int64
		summarizeBy: none
		sourceColumn: Num_mes

	column Mes
		dataType: string
		summarizeBy: none
		sourceColumn: Mes
		sortByColumn: Num_mes

	column 'Año_mes'
		dataType: string
		summarizeBy: none
		sourceColumn: Año_mes

	column Inicio_mes
		dataType: dateTime
		formatString: dd/mm/yyyy
		summarizeBy: none
		sourceColumn: Inicio_mes

		annotation UnderlyingDateTimeDataType = Date

	column Trimestre
		dataType: string
		summarizeBy: none
		sourceColumn: Trimestre

	column 'Mes_año'
		dataType: string
		summarizeBy: none
		sourceColumn: Mes_año
		sortByColumn: Inicio_mes

	/// Meses entre este mes y el último mes con sell out: 0 = mes actual, 1 = mes anterior; negativo = meses futuros.
	column Meses_atras = DATEDIFF ( Calendario[Inicio_mes], DATE ( YEAR ( MAX ( fSellOut[Datos_hasta] ) ), MONTH ( MAX ( fSellOut[Datos_hasta] ) ), 1 ), MONTH )
		dataType: int64
		formatString: 0
		summarizeBy: none

	/// Mes para los filtros: el último mes con sell out se llama "Mes actual", así el filtro guardado no se desactualiza.
	column Periodo = IF ( Calendario[Meses_atras] = 0, "Mes actual", Calendario[Mes_año] )
		dataType: string
		summarizeBy: none
		sortByColumn: Inicio_mes

	partition Calendario = m
		mode: import
		source =
				let
				    Inicio = #date(2024, 1, 1),
				    Fin = Date.EndOfYear(Date.AddMonths(DateTime.Date(DateTime.LocalNow()), 6)),
				    Fechas = List.Dates(Inicio, Duration.Days(Fin - Inicio) + 1, #duration(1, 0, 0, 0)),
				    Tabla = Table.FromList(Fechas, Splitter.SplitByNothing(), type table [Fecha = date]),
				    Anio = Table.AddColumn(Tabla, "Año", each Date.Year([Fecha]), Int64.Type),
				    NumMes = Table.AddColumn(Anio, "Num_mes", each Date.Month([Fecha]), Int64.Type),
				    Mes = Table.AddColumn(NumMes, "Mes", each Text.Proper(Date.MonthName([Fecha], "es-MX")), type text),
				    AnioMes = Table.AddColumn(Mes, "Año_mes", each Date.ToText([Fecha], "yyyy-MM"), type text),
				    InicioMes = Table.AddColumn(AnioMes, "Inicio_mes", each Date.StartOfMonth([Fecha]), type date),
				    Trimestre = Table.AddColumn(InicioMes, "Trimestre", each "T" & Text.From(Date.QuarterOfYear([Fecha])), type text),
				    // Etiqueta corta para los ejes, por ejemplo "Sep 2026"
				    MesAnio = Table.AddColumn(Trimestre, "Mes_año", each
				        {"Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"}{Date.Month([Fecha]) - 1}
				        & " " & Text.From(Date.Year([Fecha])), type text)
				in
				    MesAnio

	annotation PBI_ResultType = Table
