/// Control: archivos leídos por el reporte, sus fechas y si se usaron.
table ctlArchivos

	column Fuente
		dataType: string
		summarizeBy: none
		sourceColumn: Fuente

	column Archivo
		dataType: string
		summarizeBy: none
		sourceColumn: Archivo

	column Reporte
		dataType: string
		summarizeBy: none
		sourceColumn: Reporte

	column Desde
		dataType: dateTime
		formatString: dd/mm/yyyy
		summarizeBy: none
		sourceColumn: Desde

		annotation UnderlyingDateTimeDataType = Date

	column Hasta
		dataType: dateTime
		formatString: dd/mm/yyyy
		summarizeBy: none
		sourceColumn: Hasta

		annotation UnderlyingDateTimeDataType = Date

	column Generado
		dataType: dateTime
		formatString: dd/mm/yyyy hh:nn
		summarizeBy: none
		sourceColumn: Generado

	column Filas
		dataType: int64
		summarizeBy: none
		sourceColumn: Filas

	column Usado
		dataType: string
		summarizeBy: none
		sourceColumn: Usado

	partition ctlArchivos = m
		mode: import
		source =
				let
				    // Qué archivos leyó el reporte, de qué fechas y si se usan. Los que dicen "No" pueden pasar a la subcarpeta Respaldo.
				    DeWM = (fuente as text, t as table) as table =>
				        Table.FromRecords(List.Transform(Table.ToRecords(t), (a) => [
				            Fuente = fuente, Archivo = a[Name], Reporte = a[R][Reporte],
				            Desde = if Record.HasFields(a, "Desde") then a[Desde] else if Record.HasFields(a, "Fecha") then a[Fecha] else a[R][Desde],
				            Hasta = if Record.HasFields(a, "Hasta") then a[Hasta] else if Record.HasFields(a, "Fecha") then a[Fecha] else a[R][Hasta],
				            Generado = a[Solicitado], Filas = Table.RowCount(a[R][Datos]), Usado = a[Usado]])),
				    DeAMZ = (fuente as text, t as table) as table =>
				        Table.FromRecords(List.Transform(Table.ToRecords(t), (a) => [
				            Fuente = fuente, Archivo = a[Name], Reporte = fuente, Desde = a[Desde], Hasta = a[Hasta],
				            Generado = if a[Actualizado] = null then null else DateTime.From(a[Actualizado]),
				            Filas = Table.RowCount(a[R][Datos]), Usado = a[Usado]])),
				    UsadosFR = List.Buffer(List.Distinct(WM_FillRate_Lineas[Archivo])),
				    FillRate = Table.AddColumn(WM_FillRate_Archivos, "Usado", each
				        if List.Contains(UsadosFR, [Name]) then "Sí" else "No: todas sus órdenes están en un archivo más reciente", type text),
				    Todas = Table.Combine({
				        DeWM("Walmart - Sell out", WM_SellOut_Archivos),
				        DeWM("Walmart - Inventario", WM_Inventario_Archivos),
				        DeWM("Walmart - Fill rate", FillRate),
				        DeWM("Walmart - Forecast (Recship)", WM_Recship_Archivos),
				        DeAMZ("Amazon - Sell out", AMZ_SellOut_Archivos),
				        DeAMZ("Amazon - Inventario", AMZ_Inventario_Archivos)}),
				    Tipado = Table.TransformColumnTypes(Todas, {{"Fuente", type text}, {"Archivo", type text}, {"Reporte", type text},
				        {"Desde", type date}, {"Hasta", type date}, {"Generado", type datetime}, {"Filas", Int64.Type}, {"Usado", type text}})
				in
				    Tipado

	annotation PBI_ResultType = Table
