/// Control: archivos leídos por el reporte, sus fechas y si se usaron.
table ctlArchivos
	lineageTag: 3cacb438-079e-4d36-98c8-18db32eb79bc

	column Fuente
		dataType: string
		lineageTag: 58815bd6-1849-463f-ae0f-739f6d542ef0
		summarizeBy: none
		sourceColumn: Fuente

	column Archivo
		dataType: string
		lineageTag: 4bb6d08a-ced6-4adc-b5a3-c59e1daf16c1
		summarizeBy: none
		sourceColumn: Archivo

	column Reporte
		dataType: string
		lineageTag: f4d224cd-83fa-42da-9b63-1ffa7bd76ea8
		summarizeBy: none
		sourceColumn: Reporte

	column Desde
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 92eac1be-dcc4-4e6b-9a16-39b10a36da59
		summarizeBy: none
		sourceColumn: Desde

		annotation UnderlyingDateTimeDataType = Date

	column Hasta
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 75796ba7-eb65-416d-88f5-6a80827c6227
		summarizeBy: none
		sourceColumn: Hasta

		annotation UnderlyingDateTimeDataType = Date

	column Generado
		dataType: dateTime
		formatString: dd/mm/yyyy hh:nn
		lineageTag: 98508b0b-c604-47cc-bb6c-91b097b2fa2f
		summarizeBy: none
		sourceColumn: Generado

	column Usado
		dataType: string
		lineageTag: 18e62591-b5e1-4292-bfea-d26c27a73ab4
		summarizeBy: none
		sourceColumn: Usado

	partition ctlArchivos = m
		mode: import
		source =
				let
				    // Qué archivos leyó el reporte, de qué fechas y si se usan. Los que dicen "No" pueden pasar a la subcarpeta Respaldo.
				    DeWM = (fuente as text, t as table) as table =>
				        Table.FromRecords(List.Transform(Table.ToRecords(t), (a) => [
				            Fuente = fuente, Archivo = a[Name], Reporte = a[R][Reporte],
				            Desde = if Record.HasFields(a, "Desde") then a[Desde] else if Record.HasFields(a, "Fecha") then a[Fecha] else a[R][Desde],
				            Hasta = if Record.HasFields(a, "Hasta") then a[Hasta] else if Record.HasFields(a, "Fecha") then a[Fecha] else a[R][Hasta],
				            Generado = a[Solicitado], Usado = a[Usado]])),
				    DeAMZ = (fuente as text, t as table) as table =>
				        Table.FromRecords(List.Transform(Table.ToRecords(t), (a) => [
				            Fuente = fuente, Archivo = a[Name], Reporte = fuente, Desde = a[Desde], Hasta = a[Hasta],
				            Generado = if a[Actualizado] = null then null else DateTime.From(a[Actualizado]),
				            Usado = a[Usado]])),
				    UsadosFR = List.Buffer(List.Distinct(WM_FillRate_Lineas[Archivo])),
				    FillRate = Table.AddColumn(WM_FillRate_Archivos, "Usado", each
				        if List.Contains(UsadosFR, [Name]) then "Sí" else "No: todas sus órdenes están en un archivo más reciente", type text),
				    Todas = Table.Combine({
				        DeWM("Walmart - Sell out", WM_SellOut_Archivos),
				        DeWM("Walmart - Inventario", WM_Inventario_Archivos),
				        DeWM("Walmart - Fill rate", FillRate),
				        DeWM("Walmart - Forecast (Recship)", WM_Recship_Archivos),
				        DeAMZ("Amazon - Sell out", AMZ_SellOut_Archivos),
				        DeAMZ("Amazon - Inventario", AMZ_Inventario_Archivos)}),
				    Tipado = Table.TransformColumnTypes(Todas, {{"Fuente", type text}, {"Archivo", type text}, {"Reporte", type text},
				        {"Desde", type date}, {"Hasta", type date}, {"Generado", type datetime}, {"Usado", type text}})
				in
				    Tipado

	annotation PBI_ResultType = Table

