/// Tiendas de Walmart que aparecen en las fotos de inventario.
table dimTienda
	lineageTag: 5f92e534-0b5a-4505-a306-4d5c259587c2

	column Tienda_Nbr
		dataType: int64
		lineageTag: 64df8368-cd82-4421-b51f-c54a737fed12
		summarizeBy: none
		sourceColumn: Tienda_Nbr

	column Tienda
		dataType: string
		lineageTag: 04417fa1-0464-4b65-84ef-7a85a7559248
		summarizeBy: none
		sourceColumn: Tienda

	column Ciudad
		dataType: string
		lineageTag: f1e95c1d-cca7-46b5-9667-2bc252588ee5
		summarizeBy: none
		sourceColumn: Ciudad

	column Tienda_etiqueta
		dataType: string
		lineageTag: 176226db-02eb-4635-aa17-33e43df0d43e
		summarizeBy: none
		sourceColumn: Tienda_etiqueta

	partition dimTienda = m
		mode: import
		source =
				let
				    // Las tiendas salen de las fotos de inventario, que son pocas y pequeñas. Así no se vuelve a leer todo el sell out.
				    Filas = Table.SelectColumns(WM_Inventario_Filas, {"Store Nbr", "Store Name", "City"}),
				    Unicas = Table.Distinct(Table.SelectRows(Filas, each [Store Nbr] <> null), {"Store Nbr"}),
				    Renombrado = Table.RenameColumns(Unicas, {{"Store Nbr", "Tienda_Nbr"}, {"Store Name", "Tienda"}, {"City", "Ciudad"}}),
				    Etiqueta = Table.AddColumn(Renombrado, "Tienda_etiqueta", each Text.From([Tienda_Nbr]) & " - " & [Tienda], type text)
				in
				    Etiqueta

	annotation PBI_ResultType = Table

